spring.application.name=warPdrobe

# La URL incluye la instrucción para crear la BD si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/warPdrobe?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=1234

# Hibernate crea las tablas automáticamente a partir de tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
